### ISSUE TITLE
Viewport: replace custom intersection logic with IntersectionObserver

### ISSUE THREAD

**Issue by Vestride** [odopod/code-library#15]
Would be a breaking change because the polyfill would be required (unless it were bundled).

https://caniuse.com/#feat=intersectionobserver
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
https://github.com/w3c/IntersectionObserver/tree/master/polyfill

Viewport would become a simple wrapper around `IntersectionObserver` to determine when to call the `enter()` and `exit()` methods for items.

**Comment by glen-cheney** [comment]
closing - won't do - RIP odopod
