### ISSUE TITLE
Sassplate: CSS Grid

### ISSUE THREAD

**Issue by Vestride** [odopod/code-library#16]
How should we go about supporting CSS Grid? It's [well-supported in evergreen browsers](https://caniuse.com/#feat=css-grid).

Does it make sense to continue with our current classes (e.g. `col-4@sm`) or should we leverage some more powerful grid features?

Should we remove the `push`, `pull`, and `offset` classes with how easy CSS Grid makes this? Are there helper classes which would replace them?

I'd like to find some examples of another grid framework using CSS Grid.

**Comment by glen-cheney** [comment]
closing - won't do - RIP odopod
