### ISSUE TITLE
Dialog: Use `overscroll-behavior` instead of ScrollFix

### ISSUE THREAD

**Issue by Vestride** [odopod/code-library#9]
[Launched in Chrome 63](https://www.chromestatus.com/features/5734614437986304). Feature-detect `overscroll-behavior` and use that instead of `ScrollFix` for `OdoDialog`.

https://developers.google.com/web/updates/2017/11/overscroll-behavior

**Comment by glen-cheney** [comment]
closing - won't do - RIP odopod
